<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>demo.chess</groupId>
    <artifactId>chess-project</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Chess Project</name>
    <description>Complete Chess application build</description>

    <modules>
        <module>spring-annotation-context-initializer-template</module>
        <module>chess</module>
        <module>chess-api</module>
    </modules>

</project>
